name = "smirnova-wellbeing"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "wellbeing"
database_id = "04e94f53-01c3-4c97-9aab-279e2aaf3504"
