name = "smirnova-wellbeing"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "wellbeing"
database_id = "49390fb6-1549-4e86-90bc-ef494b0fabc4"
